<?php

namespace Tests\Feature\Budget;

use App\Models\Budget;
use App\Models\Category;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class BudgetTest extends TestCase
{
    use RefreshDatabase;
    private mixed $user;
    private mixed $budget;
    private mixed $category;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /*Log in as user as this will all be behind the log in wall*/
        $this->user = User::factory()->create();
        $this->actingAs($this->user);
        //Create's a full new budget
        $this->budget = Budget::factory()->create();
        //Create an item within the budget
        $this->category = Category::factory()->create([
            'budget_id' => $this->budget->id,
        ]);

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_budget_can_be_created(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
